[package]
name = "sherd-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "sherd-daemon"
path = "src/main.rs"

[dependencies]
sherd-core.workspace = true
sherd-platform.workspace = true
sherd-protocol.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
interprocess.workspace = true

[target.'cfg(windows)'.dependencies]
sherd-platform-windows.workspace = true
widestring.workspace = true

[target.'cfg(not(windows))'.dependencies]
sherd-platform-linux.workspace = true
