[package]
name = "daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "daemon"
path = "src/main.rs"

[dependencies]
engine.workspace = true
platform.workspace = true
protocol.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
interprocess.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[target.'cfg(windows)'.dependencies]
platform-windows.workspace = true
widestring.workspace = true
nu-ansi-term = "0.50"

[target.'cfg(not(windows))'.dependencies]
platform-linux.workspace = true
