[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
platform.workspace = true
protocol.workspace = true
tokio.workspace = true
tracing.workspace = true
sea-orm = { version = "1", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "test-util"] }
